EatCheap/Controllers/OrderController.cs
using EatCheap.Models;
using Entity;
using Manager;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EatCheap.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ProductManager productManager;
        private readonly OrderManager orderManager;
        private readonly OrderItemManager orderItemManager;

        public OrderController() 
        {
            productManager = new ProductManager();
            orderManager = new OrderManager();
            orderItemManager = new OrderItemManager();
        }
        
        
        // GET: Order
        public ActionResult Index(int id, int businessId)
        {
            /*if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(productManager.FindById(id).Data));
                Session["Cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                cart.Add(new Item(productManager.FindById(id).Data));
                Session["Cart"] = cart;
            }*/
            if (Session["cart"] == null)
            {
                List<Product> cart = new List<Product>();
                cart.Add(productManager.FindById(id).Data);
                Session["cart"] = cart;
            }
            else
            {
                List<Product> cart = (List<Product>)Session["cart"];
                cart.Add(productManager.FindById(id).Data);
                Session["cart"] = cart;
            }

            return RedirectToAction("Index", "UserProduct", new { id = businessId });
        }
        public ActionResult Order()
        {
            if (Session["cart"] != null)
            {         
                double total = 0.0;
                List<Product> list = Session["cart"] as List<Product>;
                foreach (var item in list)
	            {
                    total += item.ourPrice;		 
	            }           

                Order order = new Order()
                {
                     Date = DateTime.Now,
                      Total = total
                };

                orderManager.Create(order);

                var result = orderManager.FindAll();
                var id = (from ids in result.Data orderby ids.Id descending select ids.Id).FirstOrDefault();
           

                foreach (var item in list)
                {
                    orderItemManager.Create(new OrderItem() { OrderId = id, ProductId = item.id });
                }

                bool useSandbox = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSandbox"]);
                var paypal = new PayPal(useSandbox);

                //paypal.item_name = product;
                paypal.amount = total;
                return View("ValidateCommand", paypal);
            }
            else
            {
                return View();
            }
           
        }

        // GET: Order/Details/5
        public ActionResult Cancel()
        {
            Session.Remove("cart");
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Edit/5
        public ActionResult Edit(int id, int businessId)
        {
            List<Product> cart = (List<Product>)Session["cart"];
            Product product = productManager.FindById(id).Data;
            cart.RemoveAll(x => x.id == id);
            Session["cart"] = cart;
            return RedirectToAction("Index", "UserProduct", new { id = businessId });
        }

        // POST: Order/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Order/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult RedirectFromPaypal()
        {
            return RedirectToAction( "Index","Home");
        }

        public ActionResult CancelFromPaypal()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult NotifyFromPaypal()
        {
            return View();
        }

    }
}

EatCheap/Controllers/ProductReviewController.cs
using EatCheap.Models;
using Entity;
using Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EatCheap.Controllers
{
    [Authorize]
    public class ProductReviewController : Controller
    {
        private readonly ProductReviewManager reviewManager;

        public ProductReviewController()
        {
            this.reviewManager = new ProductReviewManager();            
        }

        // GET: ProductReview
        public ActionResult Index(int productId, int businessId)
        {

            ViewBag.ProductId = productId;
            ViewBag.BusinessId = businessId;
            var result = new Result<IEnumerable<ProductReview>>();
            try
            {
                var returnResult = reviewManager.FindByBusinessId(productId).Data;
                if (result.Ststus == ResultStatus.Success)
                {
                    result.Data = returnResult;
                    return View(result.Data);
                }
            }
            catch
            {
                return View("NOT FOUND");
            }
            return View();
        }

        // GET: ProductReview/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductReview/Create
        public ActionResult Create(int productId, int businessId)
        {
            ViewBag.ProductId = productId;
            ViewBag.BusinessId = businessId;
            return View();
        }

        // POST: ProductReview/Create
        [HttpPost]
        public ActionResult Create(ReviewVM reviewVM, int productId, int businessId)
        {
            var review = new ProductReview()
            {
                Review = reviewVM.Review,
                ProductId = productId
            };

            try
            {
                reviewManager.Create(review);
                return RedirectToAction("Index", new { productId = productId, businessId = businessId });
            }
            catch
            {
                return View("Index");
            }
        }

        // GET: ProductReview/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductReview/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductReview/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductReview/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EatCheap/Controllers/UserProductController.cs
using Entity;
using Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EatCheap.Controllers
{
    public class UserProductController : Controller
    {
        private readonly ProductManager productManager;

        public UserProductController()
        {
            this.productManager = new ProductManager();            
        }

        // GET: UserProduct
        public ActionResult Index(int id)
        {
            var result = new Result<IEnumerable<Product>>();
            try
            {
                var returnResult = productManager.FindByBusinessId(id);
                if (result.Ststus == ResultStatus.Success)
                {
                    result.Data = returnResult.Data;
                    return View(result.Data);
                }
                ViewBag.BusinessId = id;
            }
            catch (Exception)
            {
                return View("NOT FOUND");
            }
                return View(new { businessId = id });            
        }

        // GET: UserProduct/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserProduct/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserProduct/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserProduct/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UserProduct/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserProduct/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UserProduct/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EatCheap/Controllers/_vti_cnf/UserProductController.cs
vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|28 Apr 2015 03:59:42 -0000
vti_extenderversion:SR|12.0.0.0
vti_cacheddtm:TX|28 Apr 2015 03:59:42 -0000
vti_filesize:IR|2794
vti_backlinkinfo:VX|

EatCheap/Views/UserProduct/Index.cshtml
@model IEnumerable<Entity.Product>

@{
    ViewBag.Title = "Index";
}


<h2>Menu</h2>
<div class="row">
    <div class="col-md-8">
        <table class="table table-striped" style=" border-radius:5px;">
            <tr>
                <th style="width:20%">

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th style="width: 15%">
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.price)
                </th>
                <th style="color: red">
                    @Html.DisplayNameFor(model => model.ourPrice)
                </th>
                <th>    </th>

            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Content(@item.photo)" target="_blank">
                            <img src="@Url.Content(@item.photo)" height="80" width="120" />
                        </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)<br />

                        @Html.DisplayFor(modelItem => item.type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.price)
                    </td>
                    <td style="color: red">
                        @Html.DisplayFor(modelItem => item.ourPrice)
                    </td>

                    <td>
                        @Html.ActionLink("Add to Order", "Index", "Order", new { id = item.id, businessId = item.businessId }, new { @class = "btn btn-sm btn-primary" })
                        @Html.ActionLink("Reviews", "Index", "ProductReview", new { productId = item.id, businessId = item.businessId }, new { @class = "btn btn-sm btn-primary" })

                    </td>
                </tr>
            }

        </table>
        <div>
            @Html.ActionLink("Back to Places", "Index", "Home", null, new { @class = "btn btn-sm btn-primary" })
        </div>
    </div>

    <div class="col-md-4" style="margin-top: 0px">

        @if (Session["cart"] != null)
        {
            <h2 style="margin-top: 0px">Your Order</h2>
            @Html.Partial("_Cart")
            <div style="margin-top:50px">
                <table class="table table-striped" style=" border-radius:5px;">
                    <tr>
                        <th style="width:158px; height:26px;">
                           
                            @Html.ActionLink("Place Order", "Order", "Order", null, new { @class ="PayPal"  })
                        </th>
                        <th style="text-align: right">
                            @Html.ActionLink("Cancel Order", "Cancel", "Order", null, new { @class = "btn btn-sm btn-danger" })
                        </th>
                    </tr>
                </table>
            </div>

        }
    </div>
</div>




<div class="col-md-2">



</div>